/**
 * Copyright (c) 2010-2023 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

// AUTO-GENERATED by zap. DO NOT EDIT!

package org.openhab.binding.matter.internal.client.model.cluster;

import static java.util.Map.entry;

import java.util.List;
import java.util.Map;

import org.openhab.binding.matter.internal.client.MatterClient;
import org.openhab.binding.matter.internal.client.model.cluster.types.*;

/**
 * Actions
 * 
 * @author Dan Cunningham - Initial contribution
 */
public class ActionsCluster extends BaseCluster {

    public static final String CLUSTER_NAME = "ACTIONS_CLUSTER";
    public static final int CLUSTER_ID = 0x0025;

    static {
        ATTRIBUTE_MAPPING = Map.ofEntries(entry(23, "actionList"), entry(105, "endpointLists"), entry(183, "setupURL"),
                entry(13, "generatedCommandList"), entry(11, "acceptedCommandList"), entry(9, "eventList"),
                entry(7, "attributeList"), entry(5, "featureMap"), entry(2, "clusterRevision"));
        COMMAND_MAPPING = Map.ofEntries(entry(16, "instantAction"), entry(70, "instantActionWithTransition"),
                entry(119, "startAction"), entry(152, "startActionWithDuration"), entry(179, "stopAction"),
                entry(201, "pauseAction"), entry(217, "pauseActionWithDuration"), entry(230, "resumeAction"),
                entry(239, "enableAction"), entry(248, "enableActionWithDuration"), entry(256, "disableAction"),
                entry(263, "disableActionWithDuration"));
    }

    class ActionStruct implements JsonSerializable {
        public Integer actionID; // int16u
        public String name; // char_string
        public ActionTypeEnum type; // ActionTypeEnum
        public Integer endpointListID; // int16u
        public CommandBits supportedCommands; // CommandBits
        public ActionStateEnum state; // ActionStateEnum

        public ActionStruct(Integer actionID, String name, ActionTypeEnum type, Integer endpointListID,
                CommandBits supportedCommands, ActionStateEnum state) {
            this.actionID = actionID;
            this.name = name;
            this.type = type;
            this.endpointListID = endpointListID;
            this.supportedCommands = supportedCommands;
            this.state = state;
        }

        public String toJson() {
            String out = "{";
            out += "\"actionID\" : " + actionID + ",";
            out += "\"name\" : " + name + ",";
            out += "\"type\" : " + type + ",";
            out += "\"endpointListID\" : " + endpointListID + ",";
            out += "\"supportedCommands\" : " + supportedCommands + ",";
            out += "\"state\" : " + state + "";
            out += "}";
            return out;
        }
    }

    class EndpointListStruct implements JsonSerializable {
        public Integer endpointListID; // int16u
        public String name; // char_string
        public EndpointListTypeEnum type; // EndpointListTypeEnum
        public List<Integer> endpoints; // endpoint_no

        public EndpointListStruct(Integer endpointListID, String name, EndpointListTypeEnum type,
                List<Integer> endpoints) {
            this.endpointListID = endpointListID;
            this.name = name;
            this.type = type;
            this.endpoints = endpoints;
        }

        public String toJson() {
            String out = "{";
            out += "\"endpointListID\" : " + endpointListID + ",";
            out += "\"name\" : " + name + ",";
            out += "\"type\" : " + type + ",";
            out += "\"endpoints\" : " + endpoints + "";
            out += "}";
            return out;
        }
    }

    // ZCL Enums
    public enum ActionErrorEnum implements JsonSerializable {
        UNKNOWN(0, "Unknown"),
        INTERRUPTED(1, "Interrupted"),
        UNKNOWN_VALUE(2, "UnknownValue");

        public final int value;
        public final String label;

        private ActionErrorEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    public enum ActionStateEnum implements JsonSerializable {
        INACTIVE(0, "Inactive"),
        ACTIVE(1, "Active"),
        PAUSED(2, "Paused"),
        DISABLED(3, "Disabled"),
        UNKNOWN_VALUE(4, "UnknownValue");

        public final int value;
        public final String label;

        private ActionStateEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    public enum ActionTypeEnum implements JsonSerializable {
        OTHER(0, "Other"),
        SCENE(1, "Scene"),
        SEQUENCE(2, "Sequence"),
        AUTOMATION(3, "Automation"),
        EXCEPTION(4, "Exception"),
        NOTIFICATION(5, "Notification"),
        ALARM(6, "Alarm"),
        UNKNOWN_VALUE(7, "UnknownValue");

        public final int value;
        public final String label;

        private ActionTypeEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    public enum EndpointListTypeEnum implements JsonSerializable {
        OTHER(0, "Other"),
        ROOM(1, "Room"),
        ZONE(2, "Zone"),
        UNKNOWN_VALUE(3, "UnknownValue");

        public final int value;
        public final String label;

        private EndpointListTypeEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    // ZCL Bitmaps
    public static class CommandBits implements JsonSerializable {
        public boolean instantAction;
        public boolean instantActionWithTransition;
        public boolean startAction;
        public boolean startActionWithDuration;
        public boolean stopAction;
        public boolean pauseAction;
        public boolean pauseActionWithDuration;
        public boolean resumeAction;
        public boolean enableAction;
        public boolean enableActionWithDuration;
        public boolean disableAction;
        public boolean disableActionWithDuration;

        public CommandBits(boolean instantAction, boolean instantActionWithTransition, boolean startAction,
                boolean startActionWithDuration, boolean stopAction, boolean pauseAction,
                boolean pauseActionWithDuration, boolean resumeAction, boolean enableAction,
                boolean enableActionWithDuration, boolean disableAction, boolean disableActionWithDuration) {
            this.instantAction = instantAction;
            this.instantActionWithTransition = instantActionWithTransition;
            this.startAction = startAction;
            this.startActionWithDuration = startActionWithDuration;
            this.stopAction = stopAction;
            this.pauseAction = pauseAction;
            this.pauseActionWithDuration = pauseActionWithDuration;
            this.resumeAction = resumeAction;
            this.enableAction = enableAction;
            this.enableActionWithDuration = enableActionWithDuration;
            this.disableAction = disableAction;
            this.disableActionWithDuration = disableActionWithDuration;
        }

        public String toJson() {
            String out = "{";
            out += "\"instantAction\" : " + instantAction + ",";
            out += "\"instantActionWithTransition\" : " + instantActionWithTransition + ",";
            out += "\"startAction\" : " + startAction + ",";
            out += "\"startActionWithDuration\" : " + startActionWithDuration + ",";
            out += "\"stopAction\" : " + stopAction + ",";
            out += "\"pauseAction\" : " + pauseAction + ",";
            out += "\"pauseActionWithDuration\" : " + pauseActionWithDuration + ",";
            out += "\"resumeAction\" : " + resumeAction + ",";
            out += "\"enableAction\" : " + enableAction + ",";
            out += "\"enableActionWithDuration\" : " + enableActionWithDuration + ",";
            out += "\"disableAction\" : " + disableAction + ",";
            out += "\"disableActionWithDuration\" : " + disableActionWithDuration + "";
            out += "}";
            return out;
        }

        @SuppressWarnings({ "unchecked", "null" })
        public static CommandBits fromJson(String json) {
            Map<String, Boolean> m = GSON.fromJson(json, Map.class);
            Boolean[] keys = m.values().toArray(new Boolean[0]);
            return new CommandBits(keys[0], keys[1], keys[2], keys[3], keys[4], keys[5], keys[6], keys[7], keys[8],
                    keys[9], keys[10], keys[11]);
        }
    }

    public ActionStruct[] actionList; // 23 ActionStruct
    public EndpointListStruct[] endpointLists; // 105 EndpointListStruct
    public String setupURL; // 183 long_char_string
    public List<Integer> generatedCommandList; // 13 command_id
    public List<Integer> acceptedCommandList; // 11 command_id
    public List<Integer> eventList; // 9 event_id
    public List<Integer> attributeList; // 7 attrib_id
    public Map<String, Boolean> featureMap; // 5 bitmap32
    public Integer clusterRevision; // 2 int16u

    public ActionsCluster(long nodeId, int endpointId) {
        super(nodeId, endpointId, 11, "Actions");
    }

    public void instantAction(MatterClient client, Integer actionID, Integer invokeID) throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
        };
        sendCommand(client, "instantAction", o);
    }

    public void instantActionWithTransition(MatterClient client, Integer actionID, Integer invokeID,
            Integer transitionTime) throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        final Integer _transitionTime = transitionTime;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
            public Integer transitionTime = _transitionTime;
        };
        sendCommand(client, "instantActionWithTransition", o);
    }

    public void startAction(MatterClient client, Integer actionID, Integer invokeID) throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
        };
        sendCommand(client, "startAction", o);
    }

    public void startActionWithDuration(MatterClient client, Integer actionID, Integer invokeID, Integer duration)
            throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        final Integer _duration = duration;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
            public Integer duration = _duration;
        };
        sendCommand(client, "startActionWithDuration", o);
    }

    public void stopAction(MatterClient client, Integer actionID, Integer invokeID) throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
        };
        sendCommand(client, "stopAction", o);
    }

    public void pauseAction(MatterClient client, Integer actionID, Integer invokeID) throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
        };
        sendCommand(client, "pauseAction", o);
    }

    public void pauseActionWithDuration(MatterClient client, Integer actionID, Integer invokeID, Integer duration)
            throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        final Integer _duration = duration;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
            public Integer duration = _duration;
        };
        sendCommand(client, "pauseActionWithDuration", o);
    }

    public void resumeAction(MatterClient client, Integer actionID, Integer invokeID) throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
        };
        sendCommand(client, "resumeAction", o);
    }

    public void enableAction(MatterClient client, Integer actionID, Integer invokeID) throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
        };
        sendCommand(client, "enableAction", o);
    }

    public void enableActionWithDuration(MatterClient client, Integer actionID, Integer invokeID, Integer duration)
            throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        final Integer _duration = duration;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
            public Integer duration = _duration;
        };
        sendCommand(client, "enableActionWithDuration", o);
    }

    public void disableAction(MatterClient client, Integer actionID, Integer invokeID) throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
        };
        sendCommand(client, "disableAction", o);
    }

    public void disableActionWithDuration(MatterClient client, Integer actionID, Integer invokeID, Integer duration)
            throws Exception {
        final Integer _actionID = actionID;
        final Integer _invokeID = invokeID;
        final Integer _duration = duration;
        Object o = new Object() {
            public Integer actionID = _actionID;
            public Integer invokeID = _invokeID;
            public Integer duration = _duration;
        };
        sendCommand(client, "disableActionWithDuration", o);
    }

    public String toString() {
        String str = "";
        str += "actionList : " + actionList + "\n";
        str += "endpointLists : " + endpointLists + "\n";
        str += "setupURL : " + setupURL + "\n";
        str += "generatedCommandList : " + generatedCommandList + "\n";
        str += "acceptedCommandList : " + acceptedCommandList + "\n";
        str += "eventList : " + eventList + "\n";
        str += "attributeList : " + attributeList + "\n";
        str += "featureMap : " + featureMap + "\n";
        str += "clusterRevision : " + clusterRevision + "\n";
        return str;
    }
}
