/**
 * Copyright (c) 2010-2023 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

// AUTO-GENERATED by zap. DO NOT EDIT!

package org.openhab.binding.matter.internal.client.model.cluster;

import java.util.List;
import java.util.Map;

import org.openhab.binding.matter.internal.client.MatterClient;

/**
 * AdministratorCommissioning
 * 
 * @author Dan Cunningham - Initial contribution
 */
public class AdministratorCommissioningCluster extends BaseCluster {

    public static final String CLUSTER_NAME = "ADMINISTRATOR_COMMISSIONING_CLUSTER";
    public static final int CLUSTER_ID = 0x003C;

    // ZCL Enums
    public enum CommissioningWindowStatusEnum {
        WINDOWNOTOPEN(0, "WindowNotOpen"),
        ENHANCEDWINDOWOPEN(1, "EnhancedWindowOpen"),
        BASICWINDOWOPEN(2, "BasicWindowOpen"),
        UNKNOWN_VALUE(3, "UnknownValue");

        public final int value;
        public final String label;

        private CommissioningWindowStatusEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }
    };

    public enum StatusCode {
        BUSY(2, "Busy"),
        PAKEPARAMETERERROR(3, "PAKEParameterError"),
        WINDOWNOTOPEN(4, "WindowNotOpen"),
        UNKNOWN_VALUE(0, "UnknownValue");

        public final int value;
        public final String label;

        private StatusCode(int value, String label) {
            this.value = value;
            this.label = label;
        }
    };

    // ZCL Bitmaps
    public static class Feature {
        public boolean basic;

        public Feature(boolean basic) {
            this.basic = basic;
        }

        @SuppressWarnings({ "unchecked", "null" })
        public static Feature fromJson(String json) {
            Map<String, Boolean> m = GSON.fromJson(json, Map.class);
            Boolean[] keys = m.values().toArray(new Boolean[0]);
            return new Feature(keys[0]);
        }
    }

    public CommissioningWindowStatusEnum windowStatus; // 0 CommissioningWindowStatusEnum reportable
    public Integer adminFabricIndex; // 1 fabric_idx reportable
    public Integer adminVendorId; // 2 vendor_id reportable
    public List<Integer> generatedCommandList; // 65528 command_id reportable
    public List<Integer> acceptedCommandList; // 65529 command_id reportable
    public List<Integer> eventList; // 65530 event_id reportable
    public List<Integer> attributeList; // 65531 attrib_id reportable
    public Map<String, Boolean> featureMap; // 65532 bitmap32 reportable
    public Integer clusterRevision; // 65533 int16u reportable

    public AdministratorCommissioningCluster(long nodeId, int endpointId) {
        super(nodeId, endpointId, 14, "AdministratorCommissioning");
    }

    public void openCommissioningWindow(MatterClient client, Integer commissioningTimeout, String PAKEPasscodeVerifier,
            Integer discriminator, Integer iterations, String salt) throws Exception {
        final Integer _commissioningTimeout = commissioningTimeout;
        final String _PAKEPasscodeVerifier = PAKEPasscodeVerifier;
        final Integer _discriminator = discriminator;
        final Integer _iterations = iterations;
        final String _salt = salt;
        Object o = new Object() {
            public Integer commissioningTimeout = _commissioningTimeout;
            public String PAKEPasscodeVerifier = _PAKEPasscodeVerifier;
            public Integer discriminator = _discriminator;
            public Integer iterations = _iterations;
            public String salt = _salt;
        };
        sendCommand(client, "openCommissioningWindow", o);
    }

    public void openBasicCommissioningWindow(MatterClient client, Integer commissioningTimeout) throws Exception {
        final Integer _commissioningTimeout = commissioningTimeout;
        Object o = new Object() {
            public Integer commissioningTimeout = _commissioningTimeout;
        };
        sendCommand(client, "openBasicCommissioningWindow", o);
    }

    public void revokeCommissioning(MatterClient client) throws Exception {
        Object o = new Object() {
        };
        sendCommand(client, "revokeCommissioning", o);
    }

    public String toString() {
        String str = "";
        str += "windowStatus : " + windowStatus + "\n";
        str += "adminFabricIndex : " + adminFabricIndex + "\n";
        str += "adminVendorId : " + adminVendorId + "\n";
        str += "generatedCommandList : " + generatedCommandList + "\n";
        str += "acceptedCommandList : " + acceptedCommandList + "\n";
        str += "eventList : " + eventList + "\n";
        str += "attributeList : " + attributeList + "\n";
        str += "featureMap : " + featureMap + "\n";
        str += "clusterRevision : " + clusterRevision + "\n";
        return str;
    }
}
