/**
 * Copyright (c) 2010-2023 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

// AUTO-GENERATED by zap. DO NOT EDIT!

package org.openhab.binding.matter.internal.client.model.cluster;

import static java.util.Map.entry;

import java.util.List;
import java.util.Map;

import org.openhab.binding.matter.internal.client.model.cluster.types.*;

/**
 * BinaryInputBasic
 * 
 * @author Dan Cunningham - Initial contribution
 */
public class BinaryInputBasicCluster extends BaseCluster {

    public static final String CLUSTER_NAME = "BINARY_INPUT_BASIC_CLUSTER";
    public static final int CLUSTER_ID = 0x000F;

    static {
        ATTRIBUTE_MAPPING = Map.ofEntries(entry(42, "activeText"), entry(119, "description"),
                entry(192, "inactiveText"), entry(266, "outOfService"), entry(319, "polarity"),
                entry(361, "presentValue"), entry(397, "reliability"), entry(428, "statusFlags"),
                entry(456, "applicationType"), entry(13, "generatedCommandList"), entry(11, "acceptedCommandList"),
                entry(9, "eventList"), entry(7, "attributeList"), entry(5, "featureMap"), entry(2, "clusterRevision"));
        COMMAND_MAPPING = Map.ofEntries();
    }

    public String activeText; // 42 char_string
    public String description; // 119 char_string
    public String inactiveText; // 192 char_string
    public Boolean outOfService; // 266 boolean
    public Integer polarity; // 319 enum8
    public Boolean presentValue; // 361 boolean
    public Integer reliability; // 397 enum8
    public Map<String, Boolean> statusFlags; // 428 bitmap8
    public Integer applicationType; // 456 int32u
    public List<Integer> generatedCommandList; // 13 command_id
    public List<Integer> acceptedCommandList; // 11 command_id
    public List<Integer> eventList; // 9 event_id
    public List<Integer> attributeList; // 7 attrib_id
    public Map<String, Boolean> featureMap; // 5 bitmap32
    public Integer clusterRevision; // 2 int16u

    public BinaryInputBasicCluster(long nodeId, int endpointId) {
        super(nodeId, endpointId, 33, "BinaryInputBasic");
    }

    public String toString() {
        String str = "";
        str += "activeText : " + activeText + "\n";
        str += "description : " + description + "\n";
        str += "inactiveText : " + inactiveText + "\n";
        str += "outOfService : " + outOfService + "\n";
        str += "polarity : " + polarity + "\n";
        str += "presentValue : " + presentValue + "\n";
        str += "reliability : " + reliability + "\n";
        str += "statusFlags : " + statusFlags + "\n";
        str += "applicationType : " + applicationType + "\n";
        str += "generatedCommandList : " + generatedCommandList + "\n";
        str += "acceptedCommandList : " + acceptedCommandList + "\n";
        str += "eventList : " + eventList + "\n";
        str += "attributeList : " + attributeList + "\n";
        str += "featureMap : " + featureMap + "\n";
        str += "clusterRevision : " + clusterRevision + "\n";
        return str;
    }
}
