/**
 * Copyright (c) 2010-2023 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

// AUTO-GENERATED by zap. DO NOT EDIT!

package org.openhab.binding.matter.internal.client.model.cluster;

import static java.util.Map.entry;

import java.util.List;
import java.util.Map;

import org.openhab.binding.matter.internal.client.MatterClient;
import org.openhab.binding.matter.internal.client.model.cluster.types.*;

/**
 * EthernetNetworkDiagnostics
 * 
 * @author Dan Cunningham - Initial contribution
 */
public class EthernetNetworkDiagnosticsCluster extends BaseCluster {

    public static final String CLUSTER_NAME = "ETHERNET_NETWORK_DIAGNOSTICS_CLUSTER";
    public static final int CLUSTER_ID = 0x0037;

    static {
        ATTRIBUTE_MAPPING = Map.ofEntries(entry(29, "PHYRate"), entry(110, "fullDuplex"), entry(186, "packetRxCount"),
                entry(252, "packetTxCount"), entry(308, "txErrCount"), entry(352, "collisionCount"),
                entry(390, "overrunCount"), entry(423, "carrierDetect"), entry(452, "timeSinceReset"),
                entry(13, "generatedCommandList"), entry(11, "acceptedCommandList"), entry(9, "eventList"),
                entry(7, "attributeList"), entry(5, "featureMap"), entry(2, "clusterRevision"));
        COMMAND_MAPPING = Map.ofEntries(entry(14, "resetCounts"));
    }

    // ZCL Enums
    public enum PHYRateEnum implements JsonSerializable {
        RATE10M(0, "Rate10M"),
        RATE100M(1, "Rate100M"),
        RATE1G(2, "Rate1G"),
        RATE2_5G(3, "Rate2_5G"),
        RATE5G(4, "Rate5G"),
        RATE10G(5, "Rate10G"),
        RATE40G(6, "Rate40G"),
        RATE100G(7, "Rate100G"),
        RATE200G(8, "Rate200G"),
        RATE400G(9, "Rate400G"),
        UNKNOWN_VALUE(10, "UnknownValue");

        public final int value;
        public final String label;

        private PHYRateEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    // ZCL Bitmaps
    public static class Feature implements JsonSerializable {
        public boolean packetCounts;
        public boolean errorCounts;

        public Feature(boolean packetCounts, boolean errorCounts) {
            this.packetCounts = packetCounts;
            this.errorCounts = errorCounts;
        }

        public String toJson() {
            String out = "{";
            out += "\"packetCounts\" : " + packetCounts + ",";
            out += "\"errorCounts\" : " + errorCounts + "";
            out += "}";
            return out;
        }

        @SuppressWarnings({ "unchecked", "null" })
        public static Feature fromJson(String json) {
            Map<String, Boolean> m = GSON.fromJson(json, Map.class);
            Boolean[] keys = m.values().toArray(new Boolean[0]);
            return new Feature(keys[0], keys[1]);
        }
    }

    public PHYRateEnum PHYRate; // 29 PHYRateEnum
    public Boolean fullDuplex; // 110 boolean
    public Long packetRxCount; // 186 int64u
    public Long packetTxCount; // 252 int64u
    public Long txErrCount; // 308 int64u
    public Long collisionCount; // 352 int64u
    public Long overrunCount; // 390 int64u
    public Boolean carrierDetect; // 423 boolean
    public Long timeSinceReset; // 452 int64u
    public List<Integer> generatedCommandList; // 13 command_id
    public List<Integer> acceptedCommandList; // 11 command_id
    public List<Integer> eventList; // 9 event_id
    public List<Integer> attributeList; // 7 attrib_id
    public Map<String, Boolean> featureMap; // 5 bitmap32
    public Integer clusterRevision; // 2 int16u

    public EthernetNetworkDiagnosticsCluster(long nodeId, int endpointId) {
        super(nodeId, endpointId, 19, "EthernetNetworkDiagnostics");
    }

    public void resetCounts(MatterClient client) throws Exception {
        Object o = new Object() {
        };
        sendCommand(client, "resetCounts", o);
    }

    public String toString() {
        String str = "";
        str += "PHYRate : " + PHYRate + "\n";
        str += "fullDuplex : " + fullDuplex + "\n";
        str += "packetRxCount : " + packetRxCount + "\n";
        str += "packetTxCount : " + packetTxCount + "\n";
        str += "txErrCount : " + txErrCount + "\n";
        str += "collisionCount : " + collisionCount + "\n";
        str += "overrunCount : " + overrunCount + "\n";
        str += "carrierDetect : " + carrierDetect + "\n";
        str += "timeSinceReset : " + timeSinceReset + "\n";
        str += "generatedCommandList : " + generatedCommandList + "\n";
        str += "acceptedCommandList : " + acceptedCommandList + "\n";
        str += "eventList : " + eventList + "\n";
        str += "attributeList : " + attributeList + "\n";
        str += "featureMap : " + featureMap + "\n";
        str += "clusterRevision : " + clusterRevision + "\n";
        return str;
    }
}
