/**
 * Copyright (c) 2010-2023 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

// AUTO-GENERATED by zap. DO NOT EDIT!

package org.openhab.binding.matter.internal.client.model.cluster;

import static java.util.Map.entry;

import java.util.List;
import java.util.Map;

import org.openhab.binding.matter.internal.client.MatterClient;
import org.openhab.binding.matter.internal.client.model.cluster.types.*;

/**
 * GeneralDiagnostics
 * 
 * @author Dan Cunningham - Initial contribution
 */
public class GeneralDiagnosticsCluster extends BaseCluster {

    public static final String CLUSTER_NAME = "GENERAL_DIAGNOSTICS_CLUSTER";
    public static final int CLUSTER_ID = 0x0033;

    static {
        ATTRIBUTE_MAPPING = Map.ofEntries(entry(36, "networkInterfaces"), entry(115, "rebootCount"),
                entry(188, "upTime"), entry(255, "totalOperationalHours"), entry(310, "bootReason"),
                entry(353, "activeHardwareFaults"), entry(391, "activeRadioFaults"), entry(422, "activeNetworkFaults"),
                entry(451, "testEventTriggersEnabled"), entry(13, "generatedCommandList"),
                entry(11, "acceptedCommandList"), entry(9, "eventList"), entry(7, "attributeList"),
                entry(5, "featureMap"), entry(2, "clusterRevision"));
        COMMAND_MAPPING = Map.ofEntries(entry(19, "testEventTrigger"), entry(77, "timeSnapshot"),
                entry(124, "timeSnapshotResponse"));
    }

    class NetworkInterface implements JsonSerializable {
        public String name; // char_string
        public Boolean isOperational; // boolean
        public Boolean offPremiseServicesReachableIPv4; // boolean
        public Boolean offPremiseServicesReachableIPv6; // boolean
        public String hardwareAddress; // octet_string
        public String IPv4Addresses; // octet_string
        public String IPv6Addresses; // octet_string
        public InterfaceTypeEnum type; // InterfaceTypeEnum

        public NetworkInterface(String name, Boolean isOperational, Boolean offPremiseServicesReachableIPv4,
                Boolean offPremiseServicesReachableIPv6, String hardwareAddress, String IPv4Addresses,
                String IPv6Addresses, InterfaceTypeEnum type) {
            this.name = name;
            this.isOperational = isOperational;
            this.offPremiseServicesReachableIPv4 = offPremiseServicesReachableIPv4;
            this.offPremiseServicesReachableIPv6 = offPremiseServicesReachableIPv6;
            this.hardwareAddress = hardwareAddress;
            this.IPv4Addresses = IPv4Addresses;
            this.IPv6Addresses = IPv6Addresses;
            this.type = type;
        }

        public String toJson() {
            String out = "{";
            out += "\"name\" : " + name + ",";
            out += "\"isOperational\" : " + isOperational + ",";
            out += "\"offPremiseServicesReachableIPv4\" : " + offPremiseServicesReachableIPv4 + ",";
            out += "\"offPremiseServicesReachableIPv6\" : " + offPremiseServicesReachableIPv6 + ",";
            out += "\"hardwareAddress\" : " + hardwareAddress + ",";
            out += "\"IPv4Addresses\" : " + IPv4Addresses + ",";
            out += "\"IPv6Addresses\" : " + IPv6Addresses + ",";
            out += "\"type\" : " + type + "";
            out += "}";
            return out;
        }
    }

    // ZCL Enums
    public enum BootReasonEnum implements JsonSerializable {
        UNSPECIFIED(0, "Unspecified"),
        POWERONREBOOT(1, "PowerOnReboot"),
        BROWNOUTRESET(2, "BrownOutReset"),
        SOFTWAREWATCHDOGRESET(3, "SoftwareWatchdogReset"),
        HARDWAREWATCHDOGRESET(4, "HardwareWatchdogReset"),
        SOFTWAREUPDATECOMPLETED(5, "SoftwareUpdateCompleted"),
        SOFTWARERESET(6, "SoftwareReset"),
        UNKNOWN_VALUE(7, "UnknownValue");

        public final int value;
        public final String label;

        private BootReasonEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    public enum HardwareFaultEnum implements JsonSerializable {
        UNSPECIFIED(0, "Unspecified"),
        RADIO(1, "Radio"),
        SENSOR(2, "Sensor"),
        RESETTABLEOVERTEMP(3, "ResettableOverTemp"),
        NONRESETTABLEOVERTEMP(4, "NonResettableOverTemp"),
        POWERSOURCE(5, "PowerSource"),
        VISUALDISPLAYFAULT(6, "VisualDisplayFault"),
        AUDIOOUTPUTFAULT(7, "AudioOutputFault"),
        USERINTERFACEFAULT(8, "UserInterfaceFault"),
        NONVOLATILEMEMORYERROR(9, "NonVolatileMemoryError"),
        TAMPERDETECTED(10, "TamperDetected"),
        UNKNOWN_VALUE(11, "UnknownValue");

        public final int value;
        public final String label;

        private HardwareFaultEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    public enum InterfaceTypeEnum implements JsonSerializable {
        UNSPECIFIED(0, "Unspecified"),
        WIFI(1, "WiFi"),
        ETHERNET(2, "Ethernet"),
        CELLULAR(3, "Cellular"),
        THREAD(4, "Thread"),
        UNKNOWN_VALUE(5, "UnknownValue");

        public final int value;
        public final String label;

        private InterfaceTypeEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    public enum NetworkFaultEnum implements JsonSerializable {
        UNSPECIFIED(0, "Unspecified"),
        HARDWAREFAILURE(1, "HardwareFailure"),
        NETWORKJAMMED(2, "NetworkJammed"),
        CONNECTIONFAILED(3, "ConnectionFailed"),
        UNKNOWN_VALUE(4, "UnknownValue");

        public final int value;
        public final String label;

        private NetworkFaultEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    public enum RadioFaultEnum implements JsonSerializable {
        UNSPECIFIED(0, "Unspecified"),
        WIFIFAULT(1, "WiFiFault"),
        CELLULARFAULT(2, "CellularFault"),
        THREADFAULT(3, "ThreadFault"),
        NFCFAULT(4, "NFCFault"),
        BLEFAULT(5, "BLEFault"),
        ETHERNETFAULT(6, "EthernetFault"),
        UNKNOWN_VALUE(7, "UnknownValue");

        public final int value;
        public final String label;

        private RadioFaultEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    public NetworkInterface networkInterfaces; // 36 NetworkInterface
    public Integer rebootCount; // 115 int16u
    public Long upTime; // 188 int64u
    public Integer totalOperationalHours; // 255 int32u
    public BootReasonEnum bootReason; // 310 BootReasonEnum
    public HardwareFaultEnum activeHardwareFaults; // 353 HardwareFaultEnum
    public RadioFaultEnum activeRadioFaults; // 391 RadioFaultEnum
    public NetworkFaultEnum activeNetworkFaults; // 422 NetworkFaultEnum
    public Boolean testEventTriggersEnabled; // 451 boolean
    public List<Integer> generatedCommandList; // 13 command_id
    public List<Integer> acceptedCommandList; // 11 command_id
    public List<Integer> eventList; // 9 event_id
    public List<Integer> attributeList; // 7 attrib_id
    public Map<String, Boolean> featureMap; // 5 bitmap32
    public Integer clusterRevision; // 2 int16u

    public GeneralDiagnosticsCluster(long nodeId, int endpointId) {
        super(nodeId, endpointId, 26, "GeneralDiagnostics");
    }

    public void testEventTrigger(MatterClient client, String enableKey, Long eventTrigger) throws Exception {
        final String _enableKey = enableKey;
        final Long _eventTrigger = eventTrigger;
        Object o = new Object() {
            public String enableKey = _enableKey;
            public Long eventTrigger = _eventTrigger;
        };
        sendCommand(client, "testEventTrigger", o);
    }

    public void timeSnapshot(MatterClient client) throws Exception {
        Object o = new Object() {
        };
        sendCommand(client, "timeSnapshot", o);
    }

    public void timeSnapshotResponse(MatterClient client, Long systemTimeUs, Long UTCTimeUs) throws Exception {
        final Long _systemTimeUs = systemTimeUs;
        final Long _UTCTimeUs = UTCTimeUs;
        Object o = new Object() {
            public Long systemTimeUs = _systemTimeUs;
            public Long UTCTimeUs = _UTCTimeUs;
        };
        sendCommand(client, "timeSnapshotResponse", o);
    }

    public String toString() {
        String str = "";
        str += "networkInterfaces : " + networkInterfaces + "\n";
        str += "rebootCount : " + rebootCount + "\n";
        str += "upTime : " + upTime + "\n";
        str += "totalOperationalHours : " + totalOperationalHours + "\n";
        str += "bootReason : " + bootReason + "\n";
        str += "activeHardwareFaults : " + activeHardwareFaults + "\n";
        str += "activeRadioFaults : " + activeRadioFaults + "\n";
        str += "activeNetworkFaults : " + activeNetworkFaults + "\n";
        str += "testEventTriggersEnabled : " + testEventTriggersEnabled + "\n";
        str += "generatedCommandList : " + generatedCommandList + "\n";
        str += "acceptedCommandList : " + acceptedCommandList + "\n";
        str += "eventList : " + eventList + "\n";
        str += "attributeList : " + attributeList + "\n";
        str += "featureMap : " + featureMap + "\n";
        str += "clusterRevision : " + clusterRevision + "\n";
        return str;
    }
}
