/**
 * Copyright (c) 2010-2023 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

// AUTO-GENERATED by zap. DO NOT EDIT!

package org.openhab.binding.matter.internal.client.model.cluster;

import static java.util.Map.entry;

import java.util.List;
import java.util.Map;

import org.openhab.binding.matter.internal.client.model.cluster.types.*;

/**
 * LaundryWasherControls
 * 
 * @author Dan Cunningham - Initial contribution
 */
public class LaundryWasherControlsCluster extends BaseCluster {

    public static final String CLUSTER_NAME = "LAUNDRY_WASHER_CONTROLS_CLUSTER";
    public static final int CLUSTER_ID = 0x0053;

    static {
        ATTRIBUTE_MAPPING = Map.ofEntries(entry(98, "spinSpeeds"), entry(174, "spinSpeedCurrent"),
                entry(240, "numberOfRinses"), entry(297, "supportedRinses"), entry(13, "generatedCommandList"),
                entry(11, "acceptedCommandList"), entry(9, "eventList"), entry(7, "attributeList"),
                entry(5, "featureMap"), entry(2, "clusterRevision"));
        COMMAND_MAPPING = Map.ofEntries();
    }

    // ZCL Enums
    public enum NumberOfRinsesEnum implements JsonSerializable {
        NONE(0, "None"),
        NORMAL(1, "Normal"),
        EXTRA(2, "Extra"),
        MAX(3, "Max"),
        UNKNOWN_VALUE(4, "UnknownValue");

        public final int value;
        public final String label;

        private NumberOfRinsesEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    // ZCL Bitmaps
    public static class Feature implements JsonSerializable {
        public boolean spin;
        public boolean rinse;

        public Feature(boolean spin, boolean rinse) {
            this.spin = spin;
            this.rinse = rinse;
        }

        public String toJson() {
            String out = "{";
            out += "\"spin\" : " + spin + ",";
            out += "\"rinse\" : " + rinse + "";
            out += "}";
            return out;
        }

        @SuppressWarnings({ "unchecked", "null" })
        public static Feature fromJson(String json) {
            Map<String, Boolean> m = GSON.fromJson(json, Map.class);
            Boolean[] keys = m.values().toArray(new Boolean[0]);
            return new Feature(keys[0], keys[1]);
        }
    }

    public String spinSpeeds; // 98 char_string
    public Integer spinSpeedCurrent; // 174 int8u
    public NumberOfRinsesEnum numberOfRinses; // 240 NumberOfRinsesEnum
    public NumberOfRinsesEnum supportedRinses; // 297 NumberOfRinsesEnum
    public List<Integer> generatedCommandList; // 13 command_id
    public List<Integer> acceptedCommandList; // 11 command_id
    public List<Integer> eventList; // 9 event_id
    public List<Integer> attributeList; // 7 attrib_id
    public Map<String, Boolean> featureMap; // 5 bitmap32
    public Integer clusterRevision; // 2 int16u

    public LaundryWasherControlsCluster(long nodeId, int endpointId) {
        super(nodeId, endpointId, 93, "LaundryWasherControls");
    }

    public String toString() {
        String str = "";
        str += "spinSpeeds : " + spinSpeeds + "\n";
        str += "spinSpeedCurrent : " + spinSpeedCurrent + "\n";
        str += "numberOfRinses : " + numberOfRinses + "\n";
        str += "supportedRinses : " + supportedRinses + "\n";
        str += "generatedCommandList : " + generatedCommandList + "\n";
        str += "acceptedCommandList : " + acceptedCommandList + "\n";
        str += "eventList : " + eventList + "\n";
        str += "attributeList : " + attributeList + "\n";
        str += "featureMap : " + featureMap + "\n";
        str += "clusterRevision : " + clusterRevision + "\n";
        return str;
    }
}
