/**
 * Copyright (c) 2010-2023 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

// AUTO-GENERATED by zap. DO NOT EDIT!

package org.openhab.binding.matter.internal.client.model.cluster;

import static java.util.Map.entry;

import java.util.List;
import java.util.Map;

import org.openhab.binding.matter.internal.client.model.cluster.types.*;

/**
 * LocalizationConfiguration
 * 
 * @author Dan Cunningham - Initial contribution
 */
public class LocalizationConfigurationCluster extends BaseCluster {

    public static final String CLUSTER_NAME = "LOCALIZATION_CONFIGURATION_CLUSTER";
    public static final int CLUSTER_ID = 0x002B;

    static {
        ATTRIBUTE_MAPPING = Map.ofEntries(entry(46, "activeLocale"), entry(123, "supportedLocales"),
                entry(13, "generatedCommandList"), entry(11, "acceptedCommandList"), entry(9, "eventList"),
                entry(7, "attributeList"), entry(5, "featureMap"), entry(2, "clusterRevision"));
        COMMAND_MAPPING = Map.ofEntries();
    }

    public String activeLocale; // 46 char_string
    public String supportedLocales; // 123 char_string
    public List<Integer> generatedCommandList; // 13 command_id
    public List<Integer> acceptedCommandList; // 11 command_id
    public List<Integer> eventList; // 9 event_id
    public List<Integer> attributeList; // 7 attrib_id
    public Map<String, Boolean> featureMap; // 5 bitmap32
    public Integer clusterRevision; // 2 int16u

    public LocalizationConfigurationCluster(long nodeId, int endpointId) {
        super(nodeId, endpointId, 37, "LocalizationConfiguration");
    }

    public String toString() {
        String str = "";
        str += "activeLocale : " + activeLocale + "\n";
        str += "supportedLocales : " + supportedLocales + "\n";
        str += "generatedCommandList : " + generatedCommandList + "\n";
        str += "acceptedCommandList : " + acceptedCommandList + "\n";
        str += "eventList : " + eventList + "\n";
        str += "attributeList : " + attributeList + "\n";
        str += "featureMap : " + featureMap + "\n";
        str += "clusterRevision : " + clusterRevision + "\n";
        return str;
    }
}
