/**
 * Copyright (c) 2010-2024 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
// AUTO-GENERATED by zap. DO NOT EDIT!

package org.openhab.binding.matter.internal.client.model.cluster;

import java.util.List;
import java.util.Map;

/**
 * ThermostatUserInterfaceConfiguration
 * 
 * @author Dan Cunningham - Initial contribution
 */
public class ThermostatUserInterfaceConfigurationCluster extends BaseCluster {

    public static final String CLUSTER_NAME = "THERMOSTAT_USER_INTERFACE_CONFIGURATION_CLUSTER";
    public static final int CLUSTER_ID = 0x0204;

    // ZCL Enums
    public enum KeypadLockoutEnum {
        NOLOCKOUT(0, "NoLockout"),
        LOCKOUT1(1, "Lockout1"),
        LOCKOUT2(2, "Lockout2"),
        LOCKOUT3(3, "Lockout3"),
        LOCKOUT4(4, "Lockout4"),
        LOCKOUT5(5, "Lockout5"),
        UNKNOWN_VALUE(6, "UnknownValue");

        public final int value;
        public final String label;

        private KeypadLockoutEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }
    };

    public enum ScheduleProgrammingVisibilityEnum {
        SCHEDULEPROGRAMMINGPERMITTED(0, "ScheduleProgrammingPermitted"),
        SCHEDULEPROGRAMMINGDENIED(1, "ScheduleProgrammingDenied"),
        UNKNOWN_VALUE(2, "UnknownValue");

        public final int value;
        public final String label;

        private ScheduleProgrammingVisibilityEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }
    };

    public enum TemperatureDisplayModeEnum {
        CELSIUS(0, "Celsius"),
        FAHRENHEIT(1, "Fahrenheit"),
        UNKNOWN_VALUE(2, "UnknownValue");

        public final int value;
        public final String label;

        private TemperatureDisplayModeEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }
    };

    public TemperatureDisplayModeEnum temperatureDisplayMode; // 0 TemperatureDisplayModeEnum reportable writable
    public KeypadLockoutEnum keypadLockout; // 1 KeypadLockoutEnum reportable writable
    public ScheduleProgrammingVisibilityEnum scheduleProgrammingVisibility; // 2 ScheduleProgrammingVisibilityEnum
                                                                            // reportable writable
    public List<Integer> generatedCommandList; // 65528 command_id reportable
    public List<Integer> acceptedCommandList; // 65529 command_id reportable
    public List<Integer> eventList; // 65530 event_id reportable
    public List<Integer> attributeList; // 65531 attrib_id reportable
    public Map<String, Boolean> featureMap; // 65532 bitmap32 reportable
    public Integer clusterRevision; // 65533 int16u reportable

    public ThermostatUserInterfaceConfigurationCluster(long nodeId, int endpointId) {
        super(nodeId, endpointId, 84, "ThermostatUserInterfaceConfiguration");
    }

    public String toString() {
        String str = "";
        str += "temperatureDisplayMode : " + temperatureDisplayMode + "\n";
        str += "keypadLockout : " + keypadLockout + "\n";
        str += "scheduleProgrammingVisibility : " + scheduleProgrammingVisibility + "\n";
        str += "generatedCommandList : " + generatedCommandList + "\n";
        str += "acceptedCommandList : " + acceptedCommandList + "\n";
        str += "eventList : " + eventList + "\n";
        str += "attributeList : " + attributeList + "\n";
        str += "featureMap : " + featureMap + "\n";
        str += "clusterRevision : " + clusterRevision + "\n";
        return str;
    }
}
