/**
 * Copyright (c) 2010-2024 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
// AUTO-GENERATED by zap. DO NOT EDIT!

package org.openhab.binding.matter.internal.client.model.cluster;

import java.util.List;
import java.util.Map;

import org.openhab.binding.matter.internal.client.MatterClient;

/**
 * TimeSynchronization
 * 
 * @author Dan Cunningham - Initial contribution
 */
public class TimeSynchronizationCluster extends BaseCluster {

    public static final String CLUSTER_NAME = "TIME_SYNCHRONIZATION_CLUSTER";
    public static final int CLUSTER_ID = 0x0038;

    class DSTOffsetStruct {
        public Integer offset; // int32s
        public Long validStarting; // epoch_us
        public Long validUntil; // epoch_us

        public DSTOffsetStruct(Integer offset, Long validStarting, Long validUntil) {
            this.offset = offset;
            this.validStarting = validStarting;
            this.validUntil = validUntil;
        }
    }

    class FabricScopedTrustedTimeSourceStruct {
        public Long nodeID; // node_id
        public List<Integer> endpoint; // endpoint_no

        public FabricScopedTrustedTimeSourceStruct(Long nodeID, List<Integer> endpoint) {
            this.nodeID = nodeID;
            this.endpoint = endpoint;
        }
    }

    class TimeZoneStruct {
        public Integer offset; // int32s
        public Long validAt; // epoch_us
        public String name; // char_string

        public TimeZoneStruct(Integer offset, Long validAt, String name) {
            this.offset = offset;
            this.validAt = validAt;
            this.name = name;
        }
    }

    class TrustedTimeSourceStruct {
        public Integer fabricIndex; // fabric_idx
        public Long nodeID; // node_id
        public List<Integer> endpoint; // endpoint_no

        public TrustedTimeSourceStruct(Integer fabricIndex, Long nodeID, List<Integer> endpoint) {
            this.fabricIndex = fabricIndex;
            this.nodeID = nodeID;
            this.endpoint = endpoint;
        }
    }

    // ZCL Enums
    public enum GranularityEnum {
        NOTIMEGRANULARITY(0, "NoTimeGranularity"),
        MINUTESGRANULARITY(1, "MinutesGranularity"),
        SECONDSGRANULARITY(2, "SecondsGranularity"),
        MILLISECONDSGRANULARITY(3, "MillisecondsGranularity"),
        MICROSECONDSGRANULARITY(4, "MicrosecondsGranularity"),
        UNKNOWN_VALUE(5, "UnknownValue");

        public final int value;
        public final String label;

        private GranularityEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }
    };

    public enum StatusCode {
        TIMENOTACCEPTED(2, "TimeNotAccepted"),
        UNKNOWN_VALUE(0, "UnknownValue");

        public final int value;
        public final String label;

        private StatusCode(int value, String label) {
            this.value = value;
            this.label = label;
        }
    };

    public enum TimeSourceEnum {
        NONE(0, "None"),
        UNKNOWN(1, "Unknown"),
        ADMIN(2, "Admin"),
        NODETIMECLUSTER(3, "NodeTimeCluster"),
        NONMATTERSNTP(4, "NonMatterSNTP"),
        NONMATTERNTP(5, "NonMatterNTP"),
        MATTERSNTP(6, "MatterSNTP"),
        MATTERNTP(7, "MatterNTP"),
        MIXEDNTP(8, "MixedNTP"),
        NONMATTERSNTPNTS(9, "NonMatterSNTPNTS"),
        NONMATTERNTPNTS(10, "NonMatterNTPNTS"),
        MATTERSNTPNTS(11, "MatterSNTPNTS"),
        MATTERNTPNTS(12, "MatterNTPNTS"),
        MIXEDNTPNTS(13, "MixedNTPNTS"),
        CLOUDSOURCE(14, "CloudSource"),
        PTP(15, "PTP"),
        GNSS(16, "GNSS"),
        UNKNOWN_VALUE(17, "UnknownValue");

        public final int value;
        public final String label;

        private TimeSourceEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }
    };

    public enum TimeZoneDatabaseEnum {
        FULL(0, "Full"),
        PARTIAL(1, "Partial"),
        NONE(2, "None"),
        UNKNOWN_VALUE(3, "UnknownValue");

        public final int value;
        public final String label;

        private TimeZoneDatabaseEnum(int value, String label) {
            this.value = value;
            this.label = label;
        }
    };

    // ZCL Bitmaps
    public static class Feature {
        public boolean timeZone;
        public boolean NTPClient;
        public boolean NTPServer;
        public boolean timeSyncClient;

        public Feature(boolean timeZone, boolean NTPClient, boolean NTPServer, boolean timeSyncClient) {
            this.timeZone = timeZone;
            this.NTPClient = NTPClient;
            this.NTPServer = NTPServer;
            this.timeSyncClient = timeSyncClient;
        }

        @SuppressWarnings({ "unchecked", "null" })
        public static Feature fromJson(String json) {
            Map<String, Boolean> m = GSON.fromJson(json, Map.class);
            Boolean[] keys = m.values().toArray(new Boolean[0]);
            return new Feature(keys[0], keys[1], keys[2], keys[3]);
        }
    }

    public Long UTCTime; // 0 epoch_us reportable
    public GranularityEnum granularity; // 1 GranularityEnum reportable
    public TimeSourceEnum timeSource; // 2 TimeSourceEnum reportable
    public TrustedTimeSourceStruct[] trustedTimeSource; // 3 TrustedTimeSourceStruct reportable
    public String defaultNTP; // 4 char_string reportable
    public TimeZoneStruct[] timeZone; // 5 TimeZoneStruct reportable
    public DSTOffsetStruct[] DSTOffset; // 6 DSTOffsetStruct reportable
    public Long localTime; // 7 epoch_us reportable
    public TimeZoneDatabaseEnum timeZoneDatabase; // 8 TimeZoneDatabaseEnum reportable
    public Boolean NTPServerAvailable; // 9 boolean reportable
    public Integer timeZoneListMaxSize; // 10 int8u reportable
    public Integer DSTOffsetListMaxSize; // 11 int8u reportable
    public Boolean supportsDNSResolve; // 12 boolean reportable
    public List<Integer> generatedCommandList; // 65528 command_id reportable
    public List<Integer> acceptedCommandList; // 65529 command_id reportable
    public List<Integer> eventList; // 65530 event_id reportable
    public List<Integer> attributeList; // 65531 attrib_id reportable
    public Map<String, Boolean> featureMap; // 65532 bitmap32 reportable
    public Integer clusterRevision; // 65533 int16u reportable

    public TimeSynchronizationCluster(long nodeId, int endpointId) {
        super(nodeId, endpointId, 76, "TimeSynchronization");
    }

    public void setUTCTime(MatterClient client, Long UTCTime, GranularityEnum granularity, TimeSourceEnum timeSource)
            throws Exception {
        final Long _UTCTime = UTCTime;
        final GranularityEnum _granularity = granularity;
        final TimeSourceEnum _timeSource = timeSource;
        Object o = new Object() {
            public Long UTCTime = _UTCTime;
            public GranularityEnum granularity = _granularity;
            public TimeSourceEnum timeSource = _timeSource;
        };
        sendCommand(client, "setUTCTime", o);
    }

    public void setTrustedTimeSource(MatterClient client, FabricScopedTrustedTimeSourceStruct[] trustedTimeSource)
            throws Exception {
        final FabricScopedTrustedTimeSourceStruct[] _trustedTimeSource = trustedTimeSource;
        Object o = new Object() {
            public FabricScopedTrustedTimeSourceStruct[] trustedTimeSource = _trustedTimeSource;
        };
        sendCommand(client, "setTrustedTimeSource", o);
    }

    public void setTimeZone(MatterClient client, TimeZoneStruct[] timeZone) throws Exception {
        final TimeZoneStruct[] _timeZone = timeZone;
        Object o = new Object() {
            public TimeZoneStruct[] timeZone = _timeZone;
        };
        sendCommand(client, "setTimeZone", o);
    }

    public void setTimeZoneResponse(MatterClient client, Boolean DSTOffsetRequired) throws Exception {
        final Boolean _DSTOffsetRequired = DSTOffsetRequired;
        Object o = new Object() {
            public Boolean DSTOffsetRequired = _DSTOffsetRequired;
        };
        sendCommand(client, "setTimeZoneResponse", o);
    }

    public void setDSTOffset(MatterClient client, DSTOffsetStruct[] DSTOffset) throws Exception {
        final DSTOffsetStruct[] _DSTOffset = DSTOffset;
        Object o = new Object() {
            public DSTOffsetStruct[] DSTOffset = _DSTOffset;
        };
        sendCommand(client, "setDSTOffset", o);
    }

    public void setDefaultNTP(MatterClient client, String defaultNTP) throws Exception {
        final String _defaultNTP = defaultNTP;
        Object o = new Object() {
            public String defaultNTP = _defaultNTP;
        };
        sendCommand(client, "setDefaultNTP", o);
    }

    public String toString() {
        String str = "";
        str += "UTCTime : " + UTCTime + "\n";
        str += "granularity : " + granularity + "\n";
        str += "timeSource : " + timeSource + "\n";
        str += "trustedTimeSource : " + trustedTimeSource + "\n";
        str += "defaultNTP : " + defaultNTP + "\n";
        str += "timeZone : " + timeZone + "\n";
        str += "DSTOffset : " + DSTOffset + "\n";
        str += "localTime : " + localTime + "\n";
        str += "timeZoneDatabase : " + timeZoneDatabase + "\n";
        str += "NTPServerAvailable : " + NTPServerAvailable + "\n";
        str += "timeZoneListMaxSize : " + timeZoneListMaxSize + "\n";
        str += "DSTOffsetListMaxSize : " + DSTOffsetListMaxSize + "\n";
        str += "supportsDNSResolve : " + supportsDNSResolve + "\n";
        str += "generatedCommandList : " + generatedCommandList + "\n";
        str += "acceptedCommandList : " + acceptedCommandList + "\n";
        str += "eventList : " + eventList + "\n";
        str += "attributeList : " + attributeList + "\n";
        str += "featureMap : " + featureMap + "\n";
        str += "clusterRevision : " + clusterRevision + "\n";
        return str;
    }
}
