/**
 * Copyright (c) 2010-2023 Contributors to the openHAB project
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */

// AUTO-GENERATED by zap. DO NOT EDIT!

package org.openhab.binding.matter.internal.client.model.cluster;

import static java.util.Map.entry;

import java.util.List;
import java.util.Map;

import org.openhab.binding.matter.internal.client.MatterClient;
import org.openhab.binding.matter.internal.client.model.cluster.types.*;

/**
 * WindowCovering
 * 
 * @author Dan Cunningham - Initial contribution
 */
public class WindowCoveringCluster extends BaseCluster {

    public static final String CLUSTER_NAME = "WINDOW_COVERING_CLUSTER";
    public static final int CLUSTER_ID = 0x0102;

    static {
        ATTRIBUTE_MAPPING = Map.ofEntries(entry(88, "type"), entry(166, "physicalClosedLimitLift"),
                entry(233, "physicalClosedLimitTilt"), entry(291, "currentPositionLift"),
                entry(338, "currentPositionTilt"), entry(377, "numberOfActuationsLift"),
                entry(408, "numberOfActuationsTilt"), entry(439, "configStatus"),
                entry(466, "currentPositionLiftPercentage"), entry(490, "currentPositionTiltPercentage"),
                entry(513, "operationalStatus"), entry(535, "targetPositionLiftPercent100ths"),
                entry(553, "targetPositionTiltPercent100ths"), entry(571, "endProductType"),
                entry(584, "currentPositionLiftPercent100ths"), entry(597, "currentPositionTiltPercent100ths"),
                entry(609, "installedOpenLimitLift"), entry(621, "installedClosedLimitLift"),
                entry(633, "installedOpenLimitTilt"), entry(645, "installedClosedLimitTilt"), entry(657, "mode"),
                entry(669, "safetyStatus"), entry(13, "generatedCommandList"), entry(11, "acceptedCommandList"),
                entry(9, "eventList"), entry(7, "attributeList"), entry(5, "featureMap"), entry(2, "clusterRevision"));
        COMMAND_MAPPING = Map.ofEntries(entry(55, "upOrOpen"), entry(104, "downOrClose"), entry(142, "stopMotion"),
                entry(173, "goToLiftValue"), entry(196, "goToLiftPercentage"), entry(214, "goToTiltValue"),
                entry(226, "goToTiltPercentage"));
    }

    // ZCL Enums
    public enum EndProductType implements JsonSerializable {
        ROLLERSHADE(0, "RollerShade"),
        ROMANSHADE(1, "RomanShade"),
        BALLOONSHADE(2, "BalloonShade"),
        WOVENWOOD(3, "WovenWood"),
        PLEATEDSHADE(4, "PleatedShade"),
        CELLULARSHADE(5, "CellularShade"),
        LAYEREDSHADE(6, "LayeredShade"),
        LAYEREDSHADE2D(7, "LayeredShade2D"),
        SHEERSHADE(8, "SheerShade"),
        TILTONLYINTERIORBLIND(9, "TiltOnlyInteriorBlind"),
        INTERIORBLIND(10, "InteriorBlind"),
        VERTICALBLINDSTRIPCURTAIN(11, "VerticalBlindStripCurtain"),
        INTERIORVENETIANBLIND(12, "InteriorVenetianBlind"),
        EXTERIORVENETIANBLIND(13, "ExteriorVenetianBlind"),
        LATERALLEFTCURTAIN(14, "LateralLeftCurtain"),
        LATERALRIGHTCURTAIN(15, "LateralRightCurtain"),
        CENTRALCURTAIN(16, "CentralCurtain"),
        ROLLERSHUTTER(17, "RollerShutter"),
        EXTERIORVERTICALSCREEN(18, "ExteriorVerticalScreen"),
        AWNINGTERRACEPATIO(19, "AwningTerracePatio"),
        AWNINGVERTICALSCREEN(20, "AwningVerticalScreen"),
        TILTONLYPERGOLA(21, "TiltOnlyPergola"),
        SWINGINGSHUTTER(22, "SwingingShutter"),
        SLIDINGSHUTTER(23, "SlidingShutter"),
        UNKNOWN(255, "Unknown"),
        UNKNOWN_VALUE(24, "UnknownValue");

        public final int value;
        public final String label;

        private EndProductType(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    public enum Type implements JsonSerializable {
        ROLLERSHADE(0, "RollerShade"),
        ROLLERSHADE2MOTOR(1, "RollerShade2Motor"),
        ROLLERSHADEEXTERIOR(2, "RollerShadeExterior"),
        ROLLERSHADEEXTERIOR2MOTOR(3, "RollerShadeExterior2Motor"),
        DRAPERY(4, "Drapery"),
        AWNING(5, "Awning"),
        SHUTTER(6, "Shutter"),
        TILTBLINDTILTONLY(7, "TiltBlindTiltOnly"),
        TILTBLINDLIFTANDTILT(8, "TiltBlindLiftAndTilt"),
        PROJECTORSCREEN(9, "ProjectorScreen"),
        UNKNOWN(255, "Unknown"),
        UNKNOWN_VALUE(10, "UnknownValue");

        public final int value;
        public final String label;

        private Type(int value, String label) {
            this.value = value;
            this.label = label;
        }

        public String toJson() {
            return "\"" + this.label + "\"";
        }
    };

    // ZCL Bitmaps
    public static class ConfigStatus implements JsonSerializable {
        public boolean operational;
        public boolean onlineReserved;
        public boolean liftMovementReversed;
        public boolean liftPositionAware;
        public boolean tiltPositionAware;
        public boolean liftEncoderControlled;
        public boolean tiltEncoderControlled;

        public ConfigStatus(boolean operational, boolean onlineReserved, boolean liftMovementReversed,
                boolean liftPositionAware, boolean tiltPositionAware, boolean liftEncoderControlled,
                boolean tiltEncoderControlled) {
            this.operational = operational;
            this.onlineReserved = onlineReserved;
            this.liftMovementReversed = liftMovementReversed;
            this.liftPositionAware = liftPositionAware;
            this.tiltPositionAware = tiltPositionAware;
            this.liftEncoderControlled = liftEncoderControlled;
            this.tiltEncoderControlled = tiltEncoderControlled;
        }

        public String toJson() {
            String out = "{";
            out += "\"operational\" : " + operational + ",";
            out += "\"onlineReserved\" : " + onlineReserved + ",";
            out += "\"liftMovementReversed\" : " + liftMovementReversed + ",";
            out += "\"liftPositionAware\" : " + liftPositionAware + ",";
            out += "\"tiltPositionAware\" : " + tiltPositionAware + ",";
            out += "\"liftEncoderControlled\" : " + liftEncoderControlled + ",";
            out += "\"tiltEncoderControlled\" : " + tiltEncoderControlled + "";
            out += "}";
            return out;
        }

        @SuppressWarnings({ "unchecked", "null" })
        public static ConfigStatus fromJson(String json) {
            Map<String, Boolean> m = GSON.fromJson(json, Map.class);
            Boolean[] keys = m.values().toArray(new Boolean[0]);
            return new ConfigStatus(keys[0], keys[1], keys[2], keys[3], keys[4], keys[5], keys[6]);
        }
    }

    public static class Feature implements JsonSerializable {
        public boolean lift;
        public boolean tilt;
        public boolean positionAwareLift;
        public boolean absolutePosition;
        public boolean positionAwareTilt;

        public Feature(boolean lift, boolean tilt, boolean positionAwareLift, boolean absolutePosition,
                boolean positionAwareTilt) {
            this.lift = lift;
            this.tilt = tilt;
            this.positionAwareLift = positionAwareLift;
            this.absolutePosition = absolutePosition;
            this.positionAwareTilt = positionAwareTilt;
        }

        public String toJson() {
            String out = "{";
            out += "\"lift\" : " + lift + ",";
            out += "\"tilt\" : " + tilt + ",";
            out += "\"positionAwareLift\" : " + positionAwareLift + ",";
            out += "\"absolutePosition\" : " + absolutePosition + ",";
            out += "\"positionAwareTilt\" : " + positionAwareTilt + "";
            out += "}";
            return out;
        }

        @SuppressWarnings({ "unchecked", "null" })
        public static Feature fromJson(String json) {
            Map<String, Boolean> m = GSON.fromJson(json, Map.class);
            Boolean[] keys = m.values().toArray(new Boolean[0]);
            return new Feature(keys[0], keys[1], keys[2], keys[3], keys[4]);
        }
    }

    public static class Mode implements JsonSerializable {
        public boolean motorDirectionReversed;
        public boolean calibrationMode;
        public boolean maintenanceMode;
        public boolean ledFeedback;

        public Mode(boolean motorDirectionReversed, boolean calibrationMode, boolean maintenanceMode,
                boolean ledFeedback) {
            this.motorDirectionReversed = motorDirectionReversed;
            this.calibrationMode = calibrationMode;
            this.maintenanceMode = maintenanceMode;
            this.ledFeedback = ledFeedback;
        }

        public String toJson() {
            String out = "{";
            out += "\"motorDirectionReversed\" : " + motorDirectionReversed + ",";
            out += "\"calibrationMode\" : " + calibrationMode + ",";
            out += "\"maintenanceMode\" : " + maintenanceMode + ",";
            out += "\"ledFeedback\" : " + ledFeedback + "";
            out += "}";
            return out;
        }

        @SuppressWarnings({ "unchecked", "null" })
        public static Mode fromJson(String json) {
            Map<String, Boolean> m = GSON.fromJson(json, Map.class);
            Boolean[] keys = m.values().toArray(new Boolean[0]);
            return new Mode(keys[0], keys[1], keys[2], keys[3]);
        }
    }

    public static class OperationalStatus implements JsonSerializable {
        public boolean global;
        public boolean lift;
        public boolean tilt;

        public OperationalStatus(boolean global, boolean lift, boolean tilt) {
            this.global = global;
            this.lift = lift;
            this.tilt = tilt;
        }

        public String toJson() {
            String out = "{";
            out += "\"global\" : " + global + ",";
            out += "\"lift\" : " + lift + ",";
            out += "\"tilt\" : " + tilt + "";
            out += "}";
            return out;
        }

        @SuppressWarnings({ "unchecked", "null" })
        public static OperationalStatus fromJson(String json) {
            Map<String, Boolean> m = GSON.fromJson(json, Map.class);
            Boolean[] keys = m.values().toArray(new Boolean[0]);
            return new OperationalStatus(keys[0], keys[1], keys[2]);
        }
    }

    public static class SafetyStatus implements JsonSerializable {
        public boolean remoteLockout;
        public boolean tamperDetection;
        public boolean failedCommunication;
        public boolean positionFailure;
        public boolean thermalProtection;
        public boolean obstacleDetected;
        public boolean power;
        public boolean stopInput;
        public boolean motorJammed;
        public boolean hardwareFailure;
        public boolean manualOperation;
        public boolean protection;

        public SafetyStatus(boolean remoteLockout, boolean tamperDetection, boolean failedCommunication,
                boolean positionFailure, boolean thermalProtection, boolean obstacleDetected, boolean power,
                boolean stopInput, boolean motorJammed, boolean hardwareFailure, boolean manualOperation,
                boolean protection) {
            this.remoteLockout = remoteLockout;
            this.tamperDetection = tamperDetection;
            this.failedCommunication = failedCommunication;
            this.positionFailure = positionFailure;
            this.thermalProtection = thermalProtection;
            this.obstacleDetected = obstacleDetected;
            this.power = power;
            this.stopInput = stopInput;
            this.motorJammed = motorJammed;
            this.hardwareFailure = hardwareFailure;
            this.manualOperation = manualOperation;
            this.protection = protection;
        }

        public String toJson() {
            String out = "{";
            out += "\"remoteLockout\" : " + remoteLockout + ",";
            out += "\"tamperDetection\" : " + tamperDetection + ",";
            out += "\"failedCommunication\" : " + failedCommunication + ",";
            out += "\"positionFailure\" : " + positionFailure + ",";
            out += "\"thermalProtection\" : " + thermalProtection + ",";
            out += "\"obstacleDetected\" : " + obstacleDetected + ",";
            out += "\"power\" : " + power + ",";
            out += "\"stopInput\" : " + stopInput + ",";
            out += "\"motorJammed\" : " + motorJammed + ",";
            out += "\"hardwareFailure\" : " + hardwareFailure + ",";
            out += "\"manualOperation\" : " + manualOperation + ",";
            out += "\"protection\" : " + protection + "";
            out += "}";
            return out;
        }

        @SuppressWarnings({ "unchecked", "null" })
        public static SafetyStatus fromJson(String json) {
            Map<String, Boolean> m = GSON.fromJson(json, Map.class);
            Boolean[] keys = m.values().toArray(new Boolean[0]);
            return new SafetyStatus(keys[0], keys[1], keys[2], keys[3], keys[4], keys[5], keys[6], keys[7], keys[8],
                    keys[9], keys[10], keys[11]);
        }
    }

    public Type type; // 88 Type
    public Integer physicalClosedLimitLift; // 166 int16u
    public Integer physicalClosedLimitTilt; // 233 int16u
    public Integer currentPositionLift; // 291 int16u
    public Integer currentPositionTilt; // 338 int16u
    public Integer numberOfActuationsLift; // 377 int16u
    public Integer numberOfActuationsTilt; // 408 int16u
    public ConfigStatus configStatus; // 439 ConfigStatus
    public Integer currentPositionLiftPercentage; // 466 percent
    public Integer currentPositionTiltPercentage; // 490 percent
    public OperationalStatus operationalStatus; // 513 OperationalStatus
    public Integer targetPositionLiftPercent100ths; // 535 percent100ths
    public Integer targetPositionTiltPercent100ths; // 553 percent100ths
    public EndProductType endProductType; // 571 EndProductType
    public Integer currentPositionLiftPercent100ths; // 584 percent100ths
    public Integer currentPositionTiltPercent100ths; // 597 percent100ths
    public Integer installedOpenLimitLift; // 609 int16u
    public Integer installedClosedLimitLift; // 621 int16u
    public Integer installedOpenLimitTilt; // 633 int16u
    public Integer installedClosedLimitTilt; // 645 int16u
    public Mode mode; // 657 Mode
    public SafetyStatus safetyStatus; // 669 SafetyStatus
    public List<Integer> generatedCommandList; // 13 command_id
    public List<Integer> acceptedCommandList; // 11 command_id
    public List<Integer> eventList; // 9 event_id
    public List<Integer> attributeList; // 7 attrib_id
    public Map<String, Boolean> featureMap; // 5 bitmap32
    public Integer clusterRevision; // 2 int16u

    public WindowCoveringCluster(long nodeId, int endpointId) {
        super(nodeId, endpointId, 85, "WindowCovering");
    }

    public void upOrOpen(MatterClient client) throws Exception {
        Object o = new Object() {
        };
        sendCommand(client, "upOrOpen", o);
    }

    public void downOrClose(MatterClient client) throws Exception {
        Object o = new Object() {
        };
        sendCommand(client, "downOrClose", o);
    }

    public void stopMotion(MatterClient client) throws Exception {
        Object o = new Object() {
        };
        sendCommand(client, "stopMotion", o);
    }

    public void goToLiftValue(MatterClient client, Integer liftValue) throws Exception {
        final Integer _liftValue = liftValue;
        Object o = new Object() {
            public Integer liftValue = _liftValue;
        };
        sendCommand(client, "goToLiftValue", o);
    }

    public void goToLiftPercentage(MatterClient client, Integer liftPercent100thsValue) throws Exception {
        final Integer _liftPercent100thsValue = liftPercent100thsValue;
        Object o = new Object() {
            public Integer liftPercent100thsValue = _liftPercent100thsValue;
        };
        sendCommand(client, "goToLiftPercentage", o);
    }

    public void goToTiltValue(MatterClient client, Integer tiltValue) throws Exception {
        final Integer _tiltValue = tiltValue;
        Object o = new Object() {
            public Integer tiltValue = _tiltValue;
        };
        sendCommand(client, "goToTiltValue", o);
    }

    public void goToTiltPercentage(MatterClient client, Integer tiltPercent100thsValue) throws Exception {
        final Integer _tiltPercent100thsValue = tiltPercent100thsValue;
        Object o = new Object() {
            public Integer tiltPercent100thsValue = _tiltPercent100thsValue;
        };
        sendCommand(client, "goToTiltPercentage", o);
    }

    public String toString() {
        String str = "";
        str += "type : " + type + "\n";
        str += "physicalClosedLimitLift : " + physicalClosedLimitLift + "\n";
        str += "physicalClosedLimitTilt : " + physicalClosedLimitTilt + "\n";
        str += "currentPositionLift : " + currentPositionLift + "\n";
        str += "currentPositionTilt : " + currentPositionTilt + "\n";
        str += "numberOfActuationsLift : " + numberOfActuationsLift + "\n";
        str += "numberOfActuationsTilt : " + numberOfActuationsTilt + "\n";
        str += "configStatus : " + configStatus + "\n";
        str += "currentPositionLiftPercentage : " + currentPositionLiftPercentage + "\n";
        str += "currentPositionTiltPercentage : " + currentPositionTiltPercentage + "\n";
        str += "operationalStatus : " + operationalStatus + "\n";
        str += "targetPositionLiftPercent100ths : " + targetPositionLiftPercent100ths + "\n";
        str += "targetPositionTiltPercent100ths : " + targetPositionTiltPercent100ths + "\n";
        str += "endProductType : " + endProductType + "\n";
        str += "currentPositionLiftPercent100ths : " + currentPositionLiftPercent100ths + "\n";
        str += "currentPositionTiltPercent100ths : " + currentPositionTiltPercent100ths + "\n";
        str += "installedOpenLimitLift : " + installedOpenLimitLift + "\n";
        str += "installedClosedLimitLift : " + installedClosedLimitLift + "\n";
        str += "installedOpenLimitTilt : " + installedOpenLimitTilt + "\n";
        str += "installedClosedLimitTilt : " + installedClosedLimitTilt + "\n";
        str += "mode : " + mode + "\n";
        str += "safetyStatus : " + safetyStatus + "\n";
        str += "generatedCommandList : " + generatedCommandList + "\n";
        str += "acceptedCommandList : " + acceptedCommandList + "\n";
        str += "eventList : " + eventList + "\n";
        str += "attributeList : " + attributeList + "\n";
        str += "featureMap : " + featureMap + "\n";
        str += "clusterRevision : " + clusterRevision + "\n";
        return str;
    }
}
